apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goormthon-2 #FIXME:

resources:
  - backend.yaml
  - ingress.yaml # API 호출 방식이 Client-Side인 경우 주석 해제

configMapGenerator:
  - name: backend-config
    files:
      - backend-config.env=config/backend-config.env

generatorOptions:
  disableNameSuffixHash: true

  